"""Database models aggregation package."""

from backend.app.models.user import User, UserProfile, UserRole
from backend.app.models.auth import RefreshToken
from backend.app.models.payment import (
    EntitlementStatus,
    OrderStatus,
    PaymentOrder,
    PaymentTransaction,
    PremiumEntitlement,
)
from backend.app.models.audit import AuditLog
from backend.app.models.content import (
    Concept,
    ContentAccessLevel,
    ContentLevel,
    ContentStatus,
    Curriculum,
    Hint,
    Lesson,
    Problem,
    ProblemDifficulty,
    ProblemExample,
    ProblemPattern,
    Subtopic,
    Tag,
    TestCase,
    Topic,
    Track,
    problem_patterns,
    problem_tags,
)
from backend.app.models.progress import (
    LessonProgressStatus,
    Mistake,
    MistakeType,
    ProblemProgressStatus,
    ReviewOutcome,
    RevisionItem,
    RevisionSchedule,
    RevisionScheduleStatus,
    RevisionSourceType,
    Submission,
    SubmissionStatus,
    UserLessonProgress,
    UserProblemProgress,
)
from backend.app.models.judge import (
    JudgeJob,
    JudgeJobStatus,
    SubmissionResult,
    Verdict,
)
from backend.app.models.ai import (
    AIConversation,
    AIMessage,
    AIRequestType,
    AIUsage,
)

__all__ = [
    "User",
    "UserProfile",
    "UserRole",
    "RefreshToken",
    "EntitlementStatus",
    "OrderStatus",
    "PaymentOrder",
    "PaymentTransaction",
    "PremiumEntitlement",
    "AuditLog",
    "ContentLevel",
    "ContentStatus",
    "ContentAccessLevel",
    "ProblemDifficulty",
    "Curriculum",
    "Track",
    "Topic",
    "Subtopic",
    "Lesson",
    "Concept",
    "Tag",
    "ProblemPattern",
    "Problem",
    "ProblemExample",
    "Hint",
    "TestCase",
    "problem_tags",
    "problem_patterns",
    "ProblemProgressStatus",
    "LessonProgressStatus",
    "SubmissionStatus",
    "MistakeType",
    "RevisionSourceType",
    "RevisionScheduleStatus",
    "ReviewOutcome",
    "UserProblemProgress",
    "UserLessonProgress",
    "Submission",
    "Mistake",
    "RevisionItem",
    "RevisionSchedule",
    "JudgeJob",
    "JudgeJobStatus",
    "SubmissionResult",
    "Verdict",
    "AIRequestType",
    "AIUsage",
    "AIConversation",
    "AIMessage",
]

