"""Database models aggregation package."""

from backend.app.models.user import User, UserProfile, UserRole
from backend.app.models.auth import RefreshToken
from backend.app.models.payment import (
    EntitlementStatus,
    OrderStatus,
    PaymentOrder,
    PaymentTransaction,
    PremiumEntitlement,
)
from backend.app.models.audit import AuditLog
from backend.app.models.content import (
    Concept,
    ContentAccessLevel,
    ContentLevel,
    ContentStatus,
    Curriculum,
    Hint,
    Lesson,
    Problem,
    ProblemDifficulty,
    ProblemExample,
    ProblemPattern,
    Subtopic,
    Tag,
    TestCase,
    Topic,
    Track,
    problem_patterns,
    problem_tags,
)
from backend.app.models.progress import (
    LessonProgressStatus,
    Mistake,
    MistakeType,
    ProblemProgressStatus,
    ReviewOutcome,
    RevisionItem,
    RevisionSchedule,
    RevisionScheduleStatus,
    RevisionSourceType,
    Submission,
    SubmissionStatus,
    UserLessonProgress,
    UserProblemProgress,
)
from backend.app.models.judge import (
    JudgeJob,
    JudgeJobStatus,
    SubmissionResult,
    Verdict,
)
from backend.app.models.ai import (
    AIConversation,
    AIMessage,
    AIRequestType,
    AIUsage,
)
from backend.app.models.gamification import (
    Achievement,
    DailyChallenge,
    PracticeMode,
    PracticeSession,
    PracticeSessionProblem,
    PracticeSessionStatus,
    RatingHistory,
    UserAchievement,
    UserDailyChallenge,
    UserGamificationProfile,
    XPTransaction,
)
from backend.app.models.contest import (
    Contest,
    ContestCheatSignal,
    ContestParticipant,
    ContestProblem,
    ContestStatus,
    ContestSubmission,
    ContestVisibility,
)
from backend.app.models.interview import (
    InterviewMode,
    InterviewQuestion,
    InterviewSession,
    InterviewStatus,
)
from backend.app.models.cp import (
    CPProblemMetadata,
    CompetitiveRating,
    CompetitiveRatingHistory,
)
from backend.app.models.sql_learning import (
    SQLProblem,
    SQLSubmission,
)
from backend.app.models.notification import (
    DeliveryStatus,
    Notification,
    NotificationChannel,
    NotificationDelivery,
    NotificationPreference,
    NotificationType,
)


__all__ = [
    "User",
    "UserProfile",
    "UserRole",
    "RefreshToken",
    "EntitlementStatus",
    "OrderStatus",
    "PaymentOrder",
    "PaymentTransaction",
    "PremiumEntitlement",
    "AuditLog",
    "ContentLevel",
    "ContentStatus",
    "ContentAccessLevel",
    "ProblemDifficulty",
    "Curriculum",
    "Track",
    "Topic",
    "Subtopic",
    "Lesson",
    "Concept",
    "Tag",
    "ProblemPattern",
    "Problem",
    "ProblemExample",
    "Hint",
    "TestCase",
    "problem_tags",
    "problem_patterns",
    "ProblemProgressStatus",
    "LessonProgressStatus",
    "SubmissionStatus",
    "MistakeType",
    "RevisionSourceType",
    "RevisionScheduleStatus",
    "ReviewOutcome",
    "UserProblemProgress",
    "UserLessonProgress",
    "Submission",
    "Mistake",
    "RevisionItem",
    "RevisionSchedule",
    "JudgeJob",
    "JudgeJobStatus",
    "SubmissionResult",
    "Verdict",
    "AIRequestType",
    "AIUsage",
    "AIConversation",
    "AIMessage",
    "PracticeMode",
    "PracticeSessionStatus",
    "PracticeSession",
    "PracticeSessionProblem",
    "XPTransaction",
    "UserGamificationProfile",
    "DailyChallenge",
    "UserDailyChallenge",
    "Achievement",
    "UserAchievement",
    "RatingHistory",
    "Contest",
    "ContestStatus",
    "ContestVisibility",
    "ContestProblem",
    "ContestParticipant",
    "ContestSubmission",
    "ContestCheatSignal",
    "InterviewMode",
    "InterviewStatus",
    "InterviewSession",
    "InterviewQuestion",
    "CPProblemMetadata",
    "CompetitiveRating",
    "CompetitiveRatingHistory",
    "SQLProblem",
    "SQLSubmission",
    "Notification",
    "NotificationType",
    "NotificationChannel",
    "DeliveryStatus",
    "NotificationPreference",
    "NotificationDelivery",
]


