"""create phase4 progress submissions mistakes revision tables

Revision ID: 30cb1c9a63d3
Revises: 5abf95e285b6
Create Date: 2026-09-29 15:34:37.254853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30cb1c9a63d3'
down_revision: Union[str, Sequence[str], None] = '5abf95e285b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revision_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.Enum('LESSON', 'PROBLEM', 'MISTAKE', name='revisionsourcetype'), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_revision_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revision_items')),
    sa.UniqueConstraint('user_id', 'source_type', 'source_id', name='uq_user_revision_source')
    )
    op.create_index(op.f('ix_revision_items_public_id'), 'revision_items', ['public_id'], unique=True)
    op.create_index('ix_revision_items_user_active', 'revision_items', ['user_id', 'is_active'], unique=False)
    op.create_table('revision_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision_item_id', sa.String(length=36), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('interval_days', sa.Float(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'PAUSED', name='revisionschedulestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['revision_item_id'], ['revision_items.id'], name=op.f('fk_revision_schedules_revision_item_id_revision_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revision_schedules')),
    sa.UniqueConstraint('revision_item_id', name=op.f('uq_revision_schedules_revision_item_id'))
    )
    op.create_index('ix_revision_schedules_due_at', 'revision_schedules', ['due_at'], unique=False)
    op.create_index('ix_revision_schedules_status_due', 'revision_schedules', ['status', 'due_at'], unique=False)
    op.create_table('mistakes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('problem_id', sa.String(length=36), nullable=True),
    sa.Column('lesson_id', sa.String(length=36), nullable=True),
    sa.Column('mistake_type', sa.Enum('CONCEPT_GAP', 'LOGIC_ERROR', 'EDGE_CASE', 'COMPLEXITY_ISSUE', 'SYNTAX_ERROR', 'IMPLEMENTATION_ERROR', 'MISUNDERSTANDING', 'OTHER', name='mistaketype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('correction', sa.Text(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_mistakes_lesson_id_lessons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_mistakes_problem_id_problems'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mistakes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mistakes'))
    )
    op.create_index(op.f('ix_mistakes_public_id'), 'mistakes', ['public_id'], unique=True)
    op.create_index('ix_mistakes_user_created', 'mistakes', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_mistakes_user_resolved', 'mistakes', ['user_id', 'is_resolved'], unique=False)
    op.create_index('ix_mistakes_user_type', 'mistakes', ['user_id', 'mistake_type'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('source_code', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'QUEUED_FOR_FUTURE_JUDGE', 'NOT_EXECUTED', 'CANCELLED', name='submissionstatus'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_submissions_problem_id_problems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_submissions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submissions'))
    )
    op.create_index(op.f('ix_submissions_public_id'), 'submissions', ['public_id'], unique=True)
    op.create_index('ix_submissions_user_created', 'submissions', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_submissions_user_idempotency', 'submissions', ['user_id', 'idempotency_key'], unique=False)
    op.create_index('ix_submissions_user_problem', 'submissions', ['user_id', 'problem_id'], unique=False)
    op.create_index('ix_submissions_user_status', 'submissions', ['user_id', 'status'], unique=False)
    op.create_table('user_lesson_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='lessonprogressstatus'), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('progress_percent >= 0 AND progress_percent <= 100', name=op.f('ck_user_lesson_progress_chk_lesson_progress_percent')),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_user_lesson_progress_lesson_id_lessons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_lesson_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_lesson_progress')),
    sa.UniqueConstraint('user_id', 'lesson_id', name='uq_user_lesson_progress')
    )
    op.create_index('ix_user_lesson_progress_lesson_id', 'user_lesson_progress', ['lesson_id'], unique=False)
    op.create_index('ix_user_lesson_progress_user_status', 'user_lesson_progress', ['user_id', 'status'], unique=False)
    op.create_index('ix_user_lesson_progress_user_updated', 'user_lesson_progress', ['user_id', 'updated_at'], unique=False)
    op.create_table('user_problem_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'ATTEMPTED', 'SOLVED', name='problemprogressstatus'), nullable=False),
    sa.Column('attempts_count', sa.Integer(), nullable=False),
    sa.Column('successful_attempts', sa.Integer(), nullable=False),
    sa.Column('first_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('solved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bookmarked', sa.Boolean(), nullable=False),
    sa.Column('personal_difficulty', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_user_problem_progress_problem_id_problems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_problem_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_problem_progress')),
    sa.UniqueConstraint('user_id', 'problem_id', name='uq_user_problem_progress')
    )
    op.create_index('ix_user_problem_progress_problem_id', 'user_problem_progress', ['problem_id'], unique=False)
    op.create_index('ix_user_problem_progress_user_status', 'user_problem_progress', ['user_id', 'status'], unique=False)
    op.create_index('ix_user_problem_progress_user_updated', 'user_problem_progress', ['user_id', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_problem_progress_user_updated', table_name='user_problem_progress')
    op.drop_index('ix_user_problem_progress_user_status', table_name='user_problem_progress')
    op.drop_index('ix_user_problem_progress_problem_id', table_name='user_problem_progress')
    op.drop_table('user_problem_progress')
    op.drop_index('ix_user_lesson_progress_user_updated', table_name='user_lesson_progress')
    op.drop_index('ix_user_lesson_progress_user_status', table_name='user_lesson_progress')
    op.drop_index('ix_user_lesson_progress_lesson_id', table_name='user_lesson_progress')
    op.drop_table('user_lesson_progress')
    op.drop_index('ix_submissions_user_status', table_name='submissions')
    op.drop_index('ix_submissions_user_problem', table_name='submissions')
    op.drop_index('ix_submissions_user_idempotency', table_name='submissions')
    op.drop_index('ix_submissions_user_created', table_name='submissions')
    op.drop_index(op.f('ix_submissions_public_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index('ix_mistakes_user_type', table_name='mistakes')
    op.drop_index('ix_mistakes_user_resolved', table_name='mistakes')
    op.drop_index('ix_mistakes_user_created', table_name='mistakes')
    op.drop_index(op.f('ix_mistakes_public_id'), table_name='mistakes')
    op.drop_table('mistakes')
    op.drop_index('ix_revision_schedules_status_due', table_name='revision_schedules')
    op.drop_index('ix_revision_schedules_due_at', table_name='revision_schedules')
    op.drop_table('revision_schedules')
    op.drop_index('ix_revision_items_user_active', table_name='revision_items')
    op.drop_index(op.f('ix_revision_items_public_id'), table_name='revision_items')
    op.drop_table('revision_items')
    # ### end Alembic commands ###
