"""create_phase3_content_tables

Revision ID: 5abf95e285b6
Revises: 986cb3f9545d
Create Date: 2026-09-29 15:06:48.776938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5abf95e285b6'
down_revision: Union[str, Sequence[str], None] = '986cb3f9545d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concepts')),
    sa.UniqueConstraint('name', name=op.f('uq_concepts_name'))
    )
    op.create_index(op.f('ix_concepts_slug'), 'concepts', ['slug'], unique=True)
    op.create_table('curricula',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('short_description', sa.String(length=512), nullable=True),
    sa.Column('level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='contentlevel'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'PUBLISHED', 'ARCHIVED', name='contentstatus'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_curricula'))
    )
    op.create_index(op.f('ix_curricula_public_id'), 'curricula', ['public_id'], unique=True)
    op.create_index(op.f('ix_curricula_slug'), 'curricula', ['slug'], unique=True)
    op.create_index(op.f('ix_curricula_status'), 'curricula', ['status'], unique=False)
    op.create_table('patterns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patterns')),
    sa.UniqueConstraint('name', name=op.f('uq_patterns_name'))
    )
    op.create_index(op.f('ix_patterns_slug'), 'patterns', ['slug'], unique=True)
    op.create_table('tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_tags_name'))
    )
    op.create_index(op.f('ix_tags_slug'), 'tags', ['slug'], unique=True)
    op.create_table('tracks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('curriculum_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='contentlevel'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'PUBLISHED', 'ARCHIVED', name='contentstatus'), nullable=False),
    sa.Column('access_level', sa.Enum('FREE', 'PREMIUM', name='contentaccesslevel'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curricula.id'], name=op.f('fk_tracks_curriculum_id_curricula'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tracks'))
    )
    op.create_index(op.f('ix_tracks_curriculum_id'), 'tracks', ['curriculum_id'], unique=False)
    op.create_index(op.f('ix_tracks_slug'), 'tracks', ['slug'], unique=True)
    op.create_index(op.f('ix_tracks_status'), 'tracks', ['status'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('track_id', sa.String(length=36), nullable=True),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='contentlevel'), nullable=False),
    sa.Column('access_level', sa.Enum('FREE', 'PREMIUM', name='contentaccesslevel'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'PUBLISHED', 'ARCHIVED', name='contentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_topics_track_id_tracks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics'))
    )
    op.create_index(op.f('ix_topics_public_id'), 'topics', ['public_id'], unique=True)
    op.create_index(op.f('ix_topics_slug'), 'topics', ['slug'], unique=True)
    op.create_index(op.f('ix_topics_status'), 'topics', ['status'], unique=False)
    op.create_index(op.f('ix_topics_track_id'), 'topics', ['track_id'], unique=False)
    op.create_table('subtopics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='contentlevel'), nullable=False),
    sa.Column('access_level', sa.Enum('FREE', 'PREMIUM', name='contentaccesslevel'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'PUBLISHED', 'ARCHIVED', name='contentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_subtopics_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subtopics'))
    )
    op.create_index(op.f('ix_subtopics_slug'), 'subtopics', ['slug'], unique=False)
    op.create_index(op.f('ix_subtopics_status'), 'subtopics', ['status'], unique=False)
    op.create_index(op.f('ix_subtopics_topic_id'), 'subtopics', ['topic_id'], unique=False)
    op.create_index('ix_subtopics_topic_slug', 'subtopics', ['topic_id', 'slug'], unique=True)
    op.create_table('lessons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('subtopic_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='contentlevel'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('access_level', sa.Enum('FREE', 'PREMIUM', name='contentaccesslevel'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'PUBLISHED', 'ARCHIVED', name='contentstatus'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_lessons_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subtopic_id'], ['subtopics.id'], name=op.f('fk_lessons_subtopic_id_subtopics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_lessons_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lessons'))
    )
    op.create_index(op.f('ix_lessons_public_id'), 'lessons', ['public_id'], unique=True)
    op.create_index(op.f('ix_lessons_slug'), 'lessons', ['slug'], unique=True)
    op.create_index(op.f('ix_lessons_status'), 'lessons', ['status'], unique=False)
    op.create_index(op.f('ix_lessons_subtopic_id'), 'lessons', ['subtopic_id'], unique=False)
    op.create_table('problems',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', 'EXPERT', name='problemdifficulty'), nullable=False),
    sa.Column('access_level', sa.Enum('FREE', 'PREMIUM', name='contentaccesslevel'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'PUBLISHED', 'ARCHIVED', name='contentstatus'), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('subtopic_id', sa.String(length=36), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('input_format', sa.Text(), nullable=True),
    sa.Column('output_format', sa.Text(), nullable=True),
    sa.Column('constraints', sa.Text(), nullable=True),
    sa.Column('expected_time_complexity', sa.String(length=64), nullable=True),
    sa.Column('expected_space_complexity', sa.String(length=64), nullable=True),
    sa.Column('supported_languages', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_problems_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subtopic_id'], ['subtopics.id'], name=op.f('fk_problems_subtopic_id_subtopics'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_problems_topic_id_topics'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_problems_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problems'))
    )
    op.create_index(op.f('ix_problems_access_level'), 'problems', ['access_level'], unique=False)
    op.create_index(op.f('ix_problems_difficulty'), 'problems', ['difficulty'], unique=False)
    op.create_index(op.f('ix_problems_public_id'), 'problems', ['public_id'], unique=True)
    op.create_index(op.f('ix_problems_slug'), 'problems', ['slug'], unique=True)
    op.create_index(op.f('ix_problems_status'), 'problems', ['status'], unique=False)
    op.create_index(op.f('ix_problems_subtopic_id'), 'problems', ['subtopic_id'], unique=False)
    op.create_index(op.f('ix_problems_topic_id'), 'problems', ['topic_id'], unique=False)
    op.create_table('problem_examples',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('input', sa.Text(), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_problem_examples_problem_id_problems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problem_examples'))
    )
    op.create_index(op.f('ix_problem_examples_problem_id'), 'problem_examples', ['problem_id'], unique=False)
    op.create_table('problem_hints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('hint_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_problem_hints_problem_id_problems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problem_hints'))
    )
    op.create_index(op.f('ix_problem_hints_problem_id'), 'problem_hints', ['problem_id'], unique=False)
    op.create_table('problem_patterns',
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('pattern_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], name=op.f('fk_problem_patterns_pattern_id_patterns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_problem_patterns_problem_id_problems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('problem_id', 'pattern_id', name=op.f('pk_problem_patterns'))
    )
    op.create_table('problem_tags',
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_problem_tags_problem_id_problems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_problem_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('problem_id', 'tag_id', name=op.f('pk_problem_tags'))
    )
    op.create_table('test_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('input', sa.Text(), nullable=False),
    sa.Column('expected_output', sa.Text(), nullable=False),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_test_cases_problem_id_problems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_cases'))
    )
    op.create_index(op.f('ix_test_cases_is_hidden'), 'test_cases', ['is_hidden'], unique=False)
    op.create_index(op.f('ix_test_cases_problem_id'), 'test_cases', ['problem_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_cases_problem_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_is_hidden'), table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_table('problem_tags')
    op.drop_table('problem_patterns')
    op.drop_index(op.f('ix_problem_hints_problem_id'), table_name='problem_hints')
    op.drop_table('problem_hints')
    op.drop_index(op.f('ix_problem_examples_problem_id'), table_name='problem_examples')
    op.drop_table('problem_examples')
    op.drop_index(op.f('ix_problems_topic_id'), table_name='problems')
    op.drop_index(op.f('ix_problems_subtopic_id'), table_name='problems')
    op.drop_index(op.f('ix_problems_status'), table_name='problems')
    op.drop_index(op.f('ix_problems_slug'), table_name='problems')
    op.drop_index(op.f('ix_problems_public_id'), table_name='problems')
    op.drop_index(op.f('ix_problems_difficulty'), table_name='problems')
    op.drop_index(op.f('ix_problems_access_level'), table_name='problems')
    op.drop_table('problems')
    op.drop_index(op.f('ix_lessons_subtopic_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_status'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_slug'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_public_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index('ix_subtopics_topic_slug', table_name='subtopics')
    op.drop_index(op.f('ix_subtopics_topic_id'), table_name='subtopics')
    op.drop_index(op.f('ix_subtopics_status'), table_name='subtopics')
    op.drop_index(op.f('ix_subtopics_slug'), table_name='subtopics')
    op.drop_table('subtopics')
    op.drop_index(op.f('ix_topics_track_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_status'), table_name='topics')
    op.drop_index(op.f('ix_topics_slug'), table_name='topics')
    op.drop_index(op.f('ix_topics_public_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_tracks_status'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_slug'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_curriculum_id'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_patterns_slug'), table_name='patterns')
    op.drop_table('patterns')
    op.drop_index(op.f('ix_curricula_status'), table_name='curricula')
    op.drop_index(op.f('ix_curricula_slug'), table_name='curricula')
    op.drop_index(op.f('ix_curricula_public_id'), table_name='curricula')
    op.drop_table('curricula')
    op.drop_index(op.f('ix_concepts_slug'), table_name='concepts')
    op.drop_table('concepts')
    # ### end Alembic commands ###
