"""Pydantic schemas package."""
from backend.app.schemas.response import APIResponse, APIErrorResponse, APIErrorDetail
from backend.app.schemas.admin import (
    AdminUserListItem,
    AdminUserListResponse,
    AdminUserDetail,
    AdminUpdateUserRoleRequest,
    AdminUpdateUserStatusRequest,
    AdminTestCaseItem,
    AdminCreateTestCaseRequest,
    AdminUpdateTestCaseRequest,
    AdminProblemListItem,
    AdminProblemListResponse,
    SystemDiagnosticsResponse,
    AuditLogItem,
    AuditLogListResponse,
)
from backend.app.schemas.analytics import (
    PlatformOverviewMetrics,
    UserAnalyticsResponse,
    ContentAnalyticsResponse,
    GamificationAnalyticsResponse,
    CompetitionAnalyticsResponse,
    JudgeAnalyticsResponse,
    RevenueAnalyticsResponse,
    ComprehensiveAnalyticsResponse,
)
from backend.app.schemas.notification import (
    NotificationItem,
    NotificationListResponse,
    UnreadCountResponse,
    NotificationPreferenceItem,
    NotificationPreferencesResponse,
    UpdateNotificationPreferencesRequest,
    AdminBroadcastRequest,
    AdminBroadcastResponse,
)

__all__ = [
    "APIResponse",
    "APIErrorResponse",
    "APIErrorDetail",
    "AdminUserListItem",
    "AdminUserListResponse",
    "AdminUserDetail",
    "AdminUpdateUserRoleRequest",
    "AdminUpdateUserStatusRequest",
    "AdminTestCaseItem",
    "AdminCreateTestCaseRequest",
    "AdminUpdateTestCaseRequest",
    "AdminProblemListItem",
    "AdminProblemListResponse",
    "SystemDiagnosticsResponse",
    "AuditLogItem",
    "AuditLogListResponse",
    "PlatformOverviewMetrics",
    "UserAnalyticsResponse",
    "ContentAnalyticsResponse",
    "GamificationAnalyticsResponse",
    "CompetitionAnalyticsResponse",
    "JudgeAnalyticsResponse",
    "RevenueAnalyticsResponse",
    "ComprehensiveAnalyticsResponse",
    "NotificationItem",
    "NotificationListResponse",
    "UnreadCountResponse",
    "NotificationPreferenceItem",
    "NotificationPreferencesResponse",
    "UpdateNotificationPreferencesRequest",
    "AdminBroadcastRequest",
    "AdminBroadcastResponse",
]
