"""Pydantic schemas package."""

from backend.app.schemas.admin import (
    AdminCreateTestCaseRequest,
    AdminProblemListItem,
    AdminProblemListResponse,
    AdminTestCaseItem,
    AdminUpdateTestCaseRequest,
    AdminUpdateUserRoleRequest,
    AdminUpdateUserStatusRequest,
    AdminUserDetail,
    AdminUserListItem,
    AdminUserListResponse,
    AuditLogItem,
    AuditLogListResponse,
    SystemDiagnosticsResponse,
)
from backend.app.schemas.analytics import (
    CompetitionAnalyticsResponse,
    ComprehensiveAnalyticsResponse,
    ContentAnalyticsResponse,
    GamificationAnalyticsResponse,
    JudgeAnalyticsResponse,
    PlatformOverviewMetrics,
    RevenueAnalyticsResponse,
    UserAnalyticsResponse,
)
from backend.app.schemas.notification import (
    AdminBroadcastRequest,
    AdminBroadcastResponse,
    NotificationItem,
    NotificationListResponse,
    NotificationPreferenceItem,
    NotificationPreferencesResponse,
    UnreadCountResponse,
    UpdateNotificationPreferencesRequest,
)
from backend.app.schemas.response import APIErrorDetail, APIErrorResponse, APIResponse

__all__ = [
    "APIErrorDetail",
    "APIErrorResponse",
    "APIResponse",
    "AdminBroadcastRequest",
    "AdminBroadcastResponse",
    "AdminCreateTestCaseRequest",
    "AdminProblemListItem",
    "AdminProblemListResponse",
    "AdminTestCaseItem",
    "AdminUpdateTestCaseRequest",
    "AdminUpdateUserRoleRequest",
    "AdminUpdateUserStatusRequest",
    "AdminUserDetail",
    "AdminUserListItem",
    "AdminUserListResponse",
    "AuditLogItem",
    "AuditLogListResponse",
    "CompetitionAnalyticsResponse",
    "ComprehensiveAnalyticsResponse",
    "ContentAnalyticsResponse",
    "GamificationAnalyticsResponse",
    "JudgeAnalyticsResponse",
    "NotificationItem",
    "NotificationListResponse",
    "NotificationPreferenceItem",
    "NotificationPreferencesResponse",
    "PlatformOverviewMetrics",
    "RevenueAnalyticsResponse",
    "SystemDiagnosticsResponse",
    "UnreadCountResponse",
    "UpdateNotificationPreferencesRequest",
    "UserAnalyticsResponse",
]
